import rc from 'rc';

export default rc('license-report-check', {
  /*
		Full path to json file generated by 'license-report'
    describing all packages to handle..
	*/
  source: '',

  /*
		An array of license types that will not be reported.
    If this array contains license names, then packages that are
    not in this list, will be reported as 'notAllowed'.
	*/
  allowed: [],

  /*
		An array of license types that will be reported as 'forbidden'.
	*/
  forbidden: [],
});
